config/routes.rb
Quiz::Application.routes.draw do

  resources :questions, :exams, :home, :answers, :attempts
  # resources :home do
  #   collection do
  #       get '/chart/:exams', :action => 'chart'
  #     end
  #   end

  resources :users



     root :to => 'home#index'

	get '/login' => 'session#new'
	post '/login' => 'session#create'
	get '/logout' => 'session#destroy'
	get '/about' => 'home#about'
	get '/quizzes' => 'home#quizzes'
	get '/works' => 'home#works'
	get '/contact' => 'home#contact'

  root :to => 'home#index'

  post '/search/' => 'home#search'


end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                  :integer          not null, primary key
#  username            :string(255)
#  email               :string(255)
#  password_digest     :string(255)
#  location            :text
#  longitude           :float            default(0.0)
#  latitude            :float            default(0.0)
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  avatar_file_name    :string(255)
#  avatar_content_type :string(255)
#  avatar_file_size    :integer
#  avatar_updated_at   :datetime
#

class User < ActiveRecord::Base
  has_secure_password
  before_save :geocode
  attr_accessible :username, :location, :email, :password_confirmation, :password

  has_many :exams, :dependent => :destroy, :order => "created_at DESC"
  has_many :attempts, :inverse_of => :user, :dependent => :destroy, :order => "created_at DESC"

  #Paperclip avatar
  attr_accessible :avatar, :avatar_file_name, :avatar_content_type, :avatar_file_size
  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  # validates :avatar, presence: true

  delegate :avatar, :to => :user, :prefix => true, :allow_nil => true

  def user_avatar
    user.avatar if user
  end

private
  def geocode
    result = Geocoder.search(self.location).first

    if result.present?
        self.latitude = result.latitude #set latitude and longitude to our model before we save, whenever they enter an address
        self.longitude = result.longitude
      end
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :check_if_logged_in, :except => [:new, :create]
  # before_filter :check_if_admin, :only => [:destroy]


	def new
		@user = User.new
	end

  def show
    @user = User.find(params[:id])
    @exams = @user.exams
    # @exam = Exam.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

	def index
		@users = User.all
	end

	def create
		@user = User.new(params[:user])

		respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }

      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
  def check_if_logged_in
    redirect_to(login_path) if @auth.nil?
  end

  def check_if_admin
    redirect_to(root_path) if @auth.nil? || !@auth.is_admin?
  end
end

app/views/users/_form.html.haml
%div.row
	%div.col-lg-3
		= form_for @user do |f|
			%ul
				%li= f.label :username, :autofocus => true
				%li= f.text_field :username
				%li= f.label :email
				%li= f.text_field :email
				%li= f.label :password
				%li= f.password_field :password
				%li= f.label :password_confirmation
				%li= f.password_field :password_confirmation
				%li= f.label :location
				%li= f.text_field :location, :rows => 5
				%li= f.label :avatar
				%li= f.file_field :avatar
				%li= f.submit nil, :class => 'button radius'
%div.col-lg-9

app/views/users/_users.html.haml
%div.row#users
  - @users.each do |user|
    %div.col-lg-12
      - if @auth.is_admin?
        %span.label.alert= user.username
        %span= user.email

      - else
        %div.btn.btn-primary
          = link_to(user.username, user_path(user), :class => 'white')
    %div.col-lg-12
      = image_tag(user.avatar)

app/views/users/create.html.erb
<%= render(:partial => 'users') %>

app/views/users/create.js.erb
$('#new_user').fadeOut(function () { 
	$(this).empty().show();
});

$('#users').html('<%=j render(:partial => 'users')  %>');
$('#userbutton').fadeIn();

app/views/users/index.html.haml
%div#userbutton= link_to('New User', new_user_path, :remote => true, :class => 'btn btn-success btn-sm')
%div#new_user
%ul#users
= render(:partial => 'users')

app/views/users/new.html.erb
<%= render(:partial => 'form') %>

app/views/users/new.js.erb
$('#new_user').html('<%=j render(:partial => 'form') %>');
$('#userbutton').fadeOut();

app/views/users/show.html.haml
%div.col-lg-12
  %div.btn.btn-primary
    = @user.username
  %h2=@user.location
  %div.col-lg-12
    = image_tag(@user.avatar)

  %div.btn.btn-success
    %h2 See my exams
    - @exams.each do |exam|
      = link_to(exam.topic, exam)
      = time_ago_in_words(exam.created_at) + " ago"







    / = link_to('Delete My Account', @user, :method => :delete, :confirm => 'Really?', :class => 'btn btn-danger btn-sm') if @user != @auth