config/routes.rb
Quiz::Application.routes.draw do

  resources :questions, :exams, :home, :answers, :attempts
  # resources :home do
  #   collection do
  #       get '/chart/:exams', :action => 'chart'
  #     end
  #   end

  resources :users



     root :to => 'home#index'

	get '/login' => 'session#new'
	post '/login' => 'session#create'
	get '/logout' => 'session#destroy'
	get '/about' => 'home#about'
	get '/quizzes' => 'home#quizzes'
	get '/works' => 'home#works'
	get '/contact' => 'home#contact'

  root :to => 'home#index'

  post '/search/' => 'home#search'


end

app/models/exam.rb
# == Schema Information
#
# Table name: exams
#
#  id         :integer          not null, primary key
#  topic      :string(255)
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Exam < ActiveRecord::Base

  attr_accessible :topic, :user_id, :questions_attributes
  has_many :questions, :dependent => :destroy

  accepts_nested_attributes_for :questions
  belongs_to :user

  def current_exam
    current_exam = @auth.exams
  end

  def user_avatar
    user.avatar if user
  end


end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController
  def index
    @exams = Exam.all
    @users = User.all

  end

  def new
    @exam = Exam.new(params[:exam])

    10.times do
      question = @exam.questions.build
      4.times { question.answers.build}

    end
  end


  def create
    @exam = Exam.new(params[:exam])
    @exam.user_id = @auth.id
    @exam.save
    redirect_to exams_path



  end

def show

    @users = User.all
    @exam = Exam.find(params[:id])
    @questions = @exam.questions
    # @attempts = @answer.attempts
    @attempt = Attempt.new(params[:attempt])
    @exam.user_id = @auth.id
    @attempt.save


end

  def edit
   @exam = Exam.find(params[:id])

  end

  def update
    exam = Exam.find(params[:id])
    exam.update_attributes(params[:exam])
    redirect_to(exam_path)

    attempt = Attempt.new(params[:id])
    attempt.update_attributes(params[:attempt])



  end

  def destroy
    exam = Exam.find(params[:id])
    exam.destroy
    redirect_to(exam_path(current_user))
  end



end

app/views/exams/_question_fields.html.haml
%li= f.label :question, 'Enter your Question '
%li= f.text_area :question, :rows => 2
%div.row
  = f.fields_for :answers do  |answer_form|
    %div.col-lg-3
      %li= answer_form.label 'Answer '
      %li= answer_form.text_field :description
      %li= answer_form.label :correct, 'Is this the correct answer?'
      %li= answer_form.check_box :correct
%hr

app/views/exams/_results.html.erb
<div id="exam_results">
  <div class="row">
    <h3>Results</h3>
    <div class="col-lg-7">

    </div>
     <div class="col-lg-7">

    </div>
  </div>



    <h4>This <%=@exam.topic %> Quiz </h4>
  <%- @questions.each do |question| %>

    <h1>Question <%= @question_number %> - <%= question.question.capitalize %></h1>

        <% question.answers.each do |answer| %>

                <% if !answer.correct? %>
                  <% answer %>
                <% end %>
<!--
                  <!%# if answer.id == attempt.answer_id && answer.correct?%>
                  <!%# answer.attempt %>
                <!%# end %>
 -->
        <% end %>
        <% end %>


</div>

app/views/exams/index.html.haml
%div#exam-container
  = link_to('Create Exam', new_exam_path, :class => 'btn btn-success')
  %ul
    - @exams.each do |exam|
      %li.h2= exam.user.username
      / %li= exam.user.username
      %li= link_to(raw(exam.topic + '  &raquo;'), exam, :class => "btn btn-primary")
      %li= time_ago_in_words(exam.created_at) + "ago"

/ %div
/   = render "results"

app/views/exams/new.html.haml
%div.row
  %div.col-lg-12
    %div.new_exam
    %ul
      = form_for @exam do |f|
        %div.title
          = f.label :topic, 'Create an exam topic'
          %br
          = f.text_field :topic, :autofocus => true
          / = f.label 'Enter your first question'
        %div.question
          = f.fields_for :questions do |builder|
            = render "question_fields", :f => builder
        = f.submit "Submit", :class => 'btn btn-success'

app/views/exams/show.html.erb
<div id="mover">
  <%- @questions.each_with_index do |question, index| %>
  <div id="questions">
    <h4>This <%=@exam.topic %> Quiz </h4>
    <h1>Question <%= index + 1 %> - <%= question.question.capitalize %></h1>
    <h2>Pick an Answer:</h2>
    <table style="text-align: center; margin: 0 auto;">
      <tr>
        <%- question.answers.each do |answer| %>
          <td>
            <%= form_for @attempt, :remote => true do |f| %>
              <%= f.hidden_field :answer_id, :value => answer.id %>
              <%= f.hidden_field :user_id, :value => @auth.id %>

                <%= f.submit answer.description, :type => :submit, :class => "move_exam whitey" %>
                <% end %>
        </td>
        <% end %>
      </tr>
    </table>
  </div>
  <% end %>

<div id="exam_results">
  <div class="row">
       <div class="col-lg-12">
          <h4>Results</h4>
          <h4>This <%=@exam.topic %> Quiz </h4>
             <h3><span class="label label-success"> You scored 80%</span></h3>
     <!--        <div class="btn btn-success"><!% @questions.each do |question| %>
            <!% question.answers.each do |answer| %> -->

            <!-- <h7><b><!%= answer.correct? == true %> </b></h7> -->
               <!% end %>
                  <!% end %>

                </div>


        </div>

<div class="row">
<% @questions.each do |question| %>
    <div class="col-lg-3">
    <h6>Question <%= @question_number %> - <%= question.question.capitalize %></h6>

        <% question.answers.each do |answer| %>
        <span class="label label-warning"><%= answer.description %></span>
<b><%= answer.correct? %> </b>

            <% if !answer.correct? %>
                <h6><% answer.correct %></h6>
            <% end %>

    <!--           <!% if answer.id == attempt.answer_id && answer.correct? %>
              <!% answer.attempt %>
            <!% end %> -->

        <% end %>
           </div>
        <% end %>




  </div>













</div>

  </div>
  <script>

  $(document).ready(function () {
  var loading = function(e) {
    e.preventDefault();
    e.stopPropagation();
    e.target.classList.add('loading');
    e.target.setAttribute('disabled','disabled');
    setTimeout(function(){
      e.target.classList.remove('loading');
      e.target.removeAttribute('disabled');
    },1500);
  };

  var btns = document.querySelectorAll('button');
  for (var i=btns.length-1;i>=0;i--) {
    btns[i].addEventListener('click',loading);
  }

  $('.move_exam').on('click', function() {
    $(this).closest('#questions').hide();

    });



  });
</script>